
services:
  db:
    container_name: postgres
    image: postgres:18
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todo_db
      POSTGRES_USER: postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5
networks:
  db:
    driver: bridge

volumes:
  db: